# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpServerEmail < Formula
  desc "Multi-account IMAP/SMTP email MCP server (22 tools)"
  homepage "https://github.com/boutquin/mcp-server-email"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/boutquin/mcp-server-email/releases/download/v1.0.0/mcp-server-email_1.0.0_darwin_amd64.tar.gz"
      sha256 "e873fffb523dcac72a57e55a5732e2b8285997015143c7ee0732ac4b2e498db3"

      define_method(:install) do
        bin.install "mcp-server-email"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/boutquin/mcp-server-email/releases/download/v1.0.0/mcp-server-email_1.0.0_darwin_arm64.tar.gz"
      sha256 "83d667ffd24789cb5f351a805bdf8153b5f805944bc96addd9b20866b9d267d6"

      define_method(:install) do
        bin.install "mcp-server-email"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/boutquin/mcp-server-email/releases/download/v1.0.0/mcp-server-email_1.0.0_linux_amd64.tar.gz"
      sha256 "62dc12da58098fad7774a63e38895c77e45241265a9d978609c128af7629169f"
      define_method(:install) do
        bin.install "mcp-server-email"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boutquin/mcp-server-email/releases/download/v1.0.0/mcp-server-email_1.0.0_linux_arm64.tar.gz"
      sha256 "9b5bd1c4942d8020eb397b62380951a458e9c8ac3eff01a0155b7728a367a226"
      define_method(:install) do
        bin.install "mcp-server-email"
      end
    end
  end

  test do
    system "#{bin}/mcp-server-email", "--version"
  end
end
